### ISSUE TITLE
telescope integration

### ISSUE THREAD

**Issue by onelesd** [natecraddock/zf#2]
The roadmap in the readme shows telescope integration slated for release 0.2, but unless I'm crazy I don't see it in the 0.2 tag.

**Comment by natecraddock** [comment]
Release 0.2 added the libzf library. I released a telescope extension as a separate repository [telescope-zf-native.nvim](https://github.com/natecraddock/telescope-zf-native.nvim) that relies on the libzf library. Sorry the roadmap wasn't super clear, I had written the roadmap before I had started on libzf. I'll edit the readme really fast to remove that because 0.2 is out anyway.

The [changelog](https://github.com/natecraddock/zf/blob/master/CHANGELOG.md) also gives more details on libzf.

Hope that clears things up! Did you have any other questions about the telescope integration?

**Comment by onelesd** [comment]
Terrific! I didn't see that other repo. Thank you!
