### ISSUE TITLE
Improve path matching ranking

### ISSUE THREAD

**Issue by natecraddock** [natecraddock/zf#26]
Something I noticed

```
> mod/baz.rb
./app/models/foo-bar-baz.rb
./app/models/foo/bar-baz.rb
./app/models/foo/bar/baz.rb
```

In this case I think we should expect `mod/baz.rb` to rank `./app/models/foo/bar/baz.rb` the hightest because `baz.rb` has the greatest path segment coverage on that string.

**Comment by Pistos** [comment]
This is a good improvement, but when I try with version 734af10b315a87fa9ebd74c3e3417d8208b66566 , given:

```
app/models/abilities/attributes/customers.rb
app/models/user.rb
```

when I search for `ap/mod/user.rb`, the `customers.rb` is ranked higher. Perhaps this is because the `a` of `abilities` sorts alphabetically before the `u` of `user.rb` at the same level (siblings under `app/models/`)

**Comment by natecraddock** [comment]
@Pistos I'm not seeing this on my end

![image](https://user-images.githubusercontent.com/7967463/224216779-b71c6564-5e23-4c93-bbc7-98a5deb571fe.png)

**Comment by Pistos** [comment]
My bad. It was my editor doing the sorting. Sorry for the noise. :sweat_smile:

**Comment by natecraddock** [comment]
No worries! Thanks for actively reporting things :)
