### ISSUE TITLE
Support for fzf syntax

### ISSUE THREAD

**Issue by bondzula** [natecraddock/zf#50]
Hi, I've been using zf through telescope for a couple of months now, and I love it for both speed and file name matching priority. I'm just wondering if fzf compatible syntax for pattern matching is planed and  or even possible? Full disclosure: I use it rarely, but occasionally, it is helpful to have.

For reference, [telescope-fzf-native.nvim](https://github.com/nvim-telescope/telescope-fzf-native.nvim) has a nice reference table of the syntax:

![image](https://github.com/natecraddock/zf/assets/18123522/81c50a59-741f-49fc-8c6c-ccad6de7c697)

**Comment by natecraddock** [comment]
Hi @bondzula sorry for the delay on replying.

Right now I'm going to say maybe. I tried to design zf so that features like fzf search syntax aren't required. For example, instead of needing to end a query with `$` it should just match filenames with better priority. Or if you want to match the beginning of a path, usually adding in a `/` at some point would help.

But I want to balance simplicity with useful features. I'll think about this more.

Something that may help motivate me is if you can give me specific examples where this would be useful.

**Comment by bondzula** [comment]
Hi, I somehow missed this notification.

I've mainly used this syntax when exploring a new project, where maybe I want to see all files of certain file type, so `$` come in handy. But I guess you are right, just tried `.yml {search}` and it does a good job of filtering it down

**Comment by natecraddock** [comment]
No worries! Since you noticed the `.yml {search}` worked well enough, I'm not going to prioritize this feature. But I'll keep the issue open for now to see if anyone else has a compelling use case.

**Comment by bondzula** [comment]
Sounds good, Thank you!

**Comment by natecraddock** [comment]
It's been over a year and I've considered this a few times. I currently don't see the need for fzf syntax support. zf does exactly what I hoped it would do, and I don't want to complicate the implementation to add this
